const projects = [
  {
    id: 1,
    icon: '⛰',
    name: 'Expanding Cards',
    url: './expanding_cards/',
    description: 'Simple expanding cards with HTML, CSS and JavaScript',
  },
  {
    id: 2,
    icon: '👣',
    name: 'Progress Steps',
    url: './progress-steps/',
    description: 'Simple progress steps with HTML, CSS and JavaScript',
  },
  {
    id: 3,
    icon: '🐶',
    name: 'Rotating Nav Animation',
    url: './rotating-nav-animation/',
    description: 'Simple rotating nav animation with HTML, CSS and JavaScript',
  },
  {
    id: 4,
    icon: '📸',
    name: 'Blurry Loading',
    url: './blurry-loading/',
    description: 'Simple loader animation with HTML, CSS and JavaScript',
  },
  {
    id: 5,
    icon: '📜',
    name: 'Scroll Animation',
    url: './scroll-animation/',
    description: 'Simple scroll animation with HTML, CSS and JavaScript',
  },
  {
    id: 6,
    icon: '📉',
    name: 'Split Landing Page',
    url: './split-landing-page/',
    description: 'Simple split landing page with HTML, CSS and JavaScript',
  },
  {
    id: 7,
    icon: '🌊',
    name: 'Form Input Wave',
    url: './form-input-wave/',
    description: 'Simple form input wave animation with HTML, CSS and JavaScript',
  },
  {
    id: 8,
    icon: '🔊',
    name: 'Sound Board',
    url: './sound-board/',
    description: 'Simple sound board with HTML, CSS and JavaScript',
  },
  {
    id: 9,
    icon: '🃏',
    name: 'Dad Jokes',
    url: './dad-jokes/',
    description: 'Simple dad jokes with HTML, CSS and JavaScript',
  },
  {
    id: 10,
    icon: '⌨️',
    name: 'Event Keycodes',
    url: './event-keycodes/',
    description: 'Simple event keycodes with HTML, CSS and JavaScript',
  },
  {
    id: 11,
    icon: '🧞‍♀️',
    name: 'Magic Hover Effect',
    url: './magic-hover/',
    description: 'Simple magic hover effect with HTML, CSS and JavaScript',
  },
  {
    id: 12,
    icon: '📱',
    name: 'Curtain Nav Menu',
    url: './curtain-menu/',
    description: 'Simple curtain nav menu with HTML, CSS and JavaScript',
  },
  {
    id: 13,
    icon: '🤔',
    name: 'FAQ Collapse',
    url: './faq-collapse/',
    description: 'Simple FAQ collapse with HTML, CSS and JavaScript',
  },
  {
    id: 14,
    icon: '⚡️',
    name: 'Random Choice Picker',
    url: './random-choice-picker/',
    description: 'Simple random choice picker with HTML, CSS and JavaScript',
  },
  {
    id: 15,
    icon: '⏰',
    name: 'Fancy Clock',
    url: './fancy-clock/',
    description: 'Simple fancy clock with HTML, CSS and JavaScript',
  },
  {
    id: 16,
    icon: '🧭',
    name: 'Animated Navigation',
    url: './animated-navigation/',
    description: 'Simple animated navigation with HTML, CSS and JavaScript',
  },
  {
    id: 17,
    icon: '💯',
    name: 'Incrementing Counter',
    url: './incrementing-counter/',
    description: 'Simple incrementing counter with HTML, CSS and JavaScript',
  },
  {
    id: 18,
    icon: '💧',
    name: 'Drink Water',
    url: './drink-water/',
    description: 'Simple drink water with HTML, CSS and JavaScript',
  },
  {
    id: 19,
    icon: '🎬',
    name: 'Movie App',
    url: './movie-app/',
    description: 'Simple movie app with HTML, CSS and JavaScript',
  },
  {
    id: 20,
    icon: '🎴',
    name: 'Gradient Hover Card',
    url: './gradient-card/',
    description: 'Simple gradient hover card with HTML, CSS and JavaScript',
  },
  {
    id: 21,
    icon: '🌁',
    name: 'Background Slider',
    url: './background-slider/',
    description: 'Simple background slider with HTML, CSS and JavaScript',
  },
  {
    id: 22,
    icon: '🫳🏼',
    name: 'Drag N Drop',
    url: './drag-drop/',
    description: 'Simple drag and drop with HTML, Tailwind and JavaScript',
  },
  {
    id: 23,
    icon: '⌚️',
    name: 'Theme Clock',
    url: './theme-clock/',
    description: 'Simple theme clock with HTML, CSS and JavaScript',
  },
  {
    id: 24,
    icon: '🦋',
    name: 'Button Ripple Effect',
    url: './button-ripple-effect/',
    description: 'Simple button ripple effect with HTML, CSS and JavaScript',
  },
  {
    id: 25,
    icon: '✌🏼',
    name: 'Drag N Drop 2',
    url: './drag-n-drop2/',
    description: 'Simple drag and drop with HTML, CSS and JavaScript',
  },
  {
    id: 26,
    icon: '📰',
    name: 'Content Placeholder',
    url: './content-placeholder/',
    description: 'Simple content placeholder with HTML, CSS and JavaScript',
  },
  {
    id: 27,
    icon: '↕️',
    name: 'Vertical Slider',
    url: './double-vertical-slider/',
    description: 'Simple vertical slider with HTML, CSS and JavaScript',
  },
  {
    id: 28,
    icon: '🗺',
    name: 'Sticky Navbar',
    url: './sticky-navigation/',
    description: 'Simple sticky navbar with HTML, CSS and JavaScript',
  },
  {
    id: 29,
    icon: '❤️',
    name: 'Double Click Heart',
    url: './double-click-heart/',
    description: 'Simple double click heart with HTML, CSS and JavaScript',
  },
  {
    id: 30,
    icon: '💬',
    name: 'Auto Text Effect',
    url: './auto-text-effect/',
    description: 'Simple auto text effect with HTML, CSS and JavaScript',
  },
  {
    id: 31,
    icon: '🔑',
    name: 'Password Generator',
    url: './password-generator/',
    description: 'Simple password generator with HTML, CSS and JavaScript',
  },
  {
    id: 32,
    icon: '☠️',
    name: 'Hacked Text Effect',
    url: './hacked-text-effect/',
    description: 'Simple hacked text effect with HTML, CSS and JavaScript',
  },
  {
    id: 33,
    icon: '🗒',
    name: 'Notes App',
    url: './notes-app/',
    description: 'Simple notes app with HTML, CSS and JavaScript',
  },
  {
    id: 34,
    icon: '3️⃣',
    name: 'Animated Countdown',
    url: './animated-countdown/',
    description: 'Simple animated countdown with HTML, CSS and JavaScript',
  },
  {
    id: 35,
    icon: '🛤',
    name: 'Sliding Image Track',
    url: './sliding-image-track/',
    description: 'Simple image sliding track with HTML, CSS and JavaScript',
  },
  {
    id: 36,
    icon: '🟪',
    name: 'Hoverboard',
    url: './hoverboard/',
    description: 'Simple hoverboard with HTML, CSS and JavaScript',
  },
  {
    id: 37,
    icon: '🤹🏼‍♀️',
    name: 'CSS Popout Menu',
    url: './css-popover/',
    description: 'Simple CSS popout menu with HTML, CSS and JavaScript',
  },
  {
    id: 38,
    icon: '🦖',
    name: 'Pokedex',
    url: './pokedex/',
    description: 'Simple pokedex with HTML, CSS and JavaScript',
  },
  {
    id: 39,
    icon: '＃',
    name: 'Staggered Grid',
    url: './staggered-grid-effect/',
    description: 'Simple staggered grid with HTML, CSS, AnimeJS and JavaScript',
  },
  {
    id: 40,
    icon: '📆',
    name: 'Locale Calendar',
    url: './locale-calendar/',
    description: 'Simple locale calendar with HTML, CSS and JavaScript',
  },
];

export default projects;
export { projects };